### ISSUE TITLE
[Bug?] Menu and Keyboard stay behind when teleporting

### ISSUE THREAD

**Issue by sealotus94** [InflexionPoint/ByldrFeedback#89] opened 2020-11-21 21:46 UTC
I've noticed that the settings menu and the keyboard stay behind where I first appear when I create a new byld. Could you please make it follow me like the "Object Option" menu which appears wherever I am as I teleport around the scene? 
![image](https://user-images.githubusercontent.com/31398243/99888200-88229a00-2c10-11eb-9973-b2dd67a1a1d2.png)

**Comment by s4t0** [comment] 2020-12-22 00:32
this a duplicate of issue #85 closing this please refer to the other

**Closed as completed by s4t0** 2020-12-22 00:32 UTC
