### ISSUE TITLE
[Bug?] Multi User Byld Button has a weird detection zone/hit box/hit text

### ISSUE THREAD

**Issue by sealotus94** [InflexionPoint/ByldrFeedback#87] opened 2020-11-19 18:25 UTC
I'm trying to make a tutorial video with multi user bylds and the detection zone of the button isn't working like the button below. I have to tap on a very specific area see video below: 
https://gph.is/g/E0p86bY

**Comment by s4t0** [comment] 2021-01-06 20:06
this is a duplicate of #60

**Closed as completed** 2021-01-22 06:35 UTC
Labels: duplicate
