### ISSUE TITLE
[BUG] Clear objects feature. After clearing objects, hierarchy list is empty, but the scene still shows objects

### ISSUE THREAD

**Issue by decea89** [InflexionPoint/ByldrFeedback#86] opened 2020-11-19 16:37 UTC
Take a look at the following two images (They are named in order of action). The second one, after clearing the objects, shows the empty list but my objects are still there (orange box at the right side)

![clearObjects_1](https://user-images.githubusercontent.com/15913221/99695360-c6438080-2a8d-11eb-9300-5047f4ef3c6b.jpg)
![clearObjects_2](https://user-images.githubusercontent.com/15913221/99695365-c6dc1700-2a8d-11eb-9af0-fb5c5276613b.jpg)

**Comment by s4t0** [comment] 2021-01-06 20:42
this is a duplicate of #61

**Comment by mr0ng** [comment] 2021-01-06 20:44
Closing this, since it's a duplicate bug report

**Closed as completed by mr0ng** 2021-01-06 20:44 UTC
Labels: duplicate
