### ISSUE TITLE
[Bug] Wrong position when putting HMD off and on

### ISSUE THREAD

**Issue by Acimaz** [InflexionPoint/ByldrFeedback#41] opened 2020-11-04 10:21 UTC
Sometimes when you put off the HMD and put it on again, you are in a completely different position and can see the menus floating on your previous position.

**Comment by mr0ng** [comment] 2021-01-29 14:26
We are closing this issue for now, as the issue is related to Oculus Quest tracking rather than the Byldr app. We are unable to reproduce this specifically for Byldr. We've noticed this happening even with the oculus home screen as well. If you feel that this issue is specific to Byldr, feel free to re-open or open a new issue and we can investigate further.

**Closed as completed by mr0ng** 2021-01-29 14:26 UTC
Labels: bug, Tracked
