### ISSUE TITLE
[Feature Request]UI windows dragging

### ISSUE THREAD

**Issue by HoloKalasha666** [InflexionPoint/ByldrFeedback#66] opened 2020-11-10 16:21 UTC
Give a user an opportunity to drag a UI window while holding a background, not only a title

**Comment by mr0ng** [comment] 2021-01-22 06:47
Appears to be duplicate of #23 - will close this issue and continue to monitor and address the duplicate issue. Let me know if you feel these are separate issues.

**Closed as completed by mr0ng** 2021-01-22 06:47 UTC
Labels: enhancement, Tracked
